### PR TITLE
Item status updates and error handling

### LINKED ISSUE #31: Merchant Items Grouped by Status
As a merchant,
When I visit my merchant items index page
Then I see two sections, one for "Enabled Items" and one for "Disabled Items"
And I see that each Item is listed in the appropriate section

### LINKED ISSUE #32: Merchant Item Disable/Enable
As a merchant
When I visit my items index page
Next to each item name I see a button to disable or enable that item.
When I click this button
Then I am redirected back to the items index
And I see that the items status has changed

### LINKED ISSUE #51: Deal with sad paths and success messages for Merchant Item updates
Need to update merchant item update action to include relevant messages for successful and failed updates.

### PR DESCRIPTION
**Pull request by mkrumholz**
## Changes

- Added validations to Item class
- Added error and success messaging for Item updates
- Updated pricing display and conversion logic for proper MVC principles
- Added column to Items table for enabled/disabled
- Created categories for displaying enabled/disabled items on index page
- Added buttons for enabling/disabling items from index page
- Added edit form and ability to edit Item attributes
- Added a module to deal with price conversions

## Special review requests

I would love some extra review on my Merchants/Items controller, especially the update action and structure of the module, etc. Any thoughts on how I could make this better or more streamlined? Thanks!

## Checklist
- [x] Tests written where required
- [x] All tests passing -- No, only test failing deals with the issue above in special review.
- [x] SimpleCov at 100% 

closes #31 
closes #32 
closes #51

### CODE REVIEW

File: app/controllers/merchants/items_controller.rb [hunk 1]
```diff
@@ -1,32 +1,47 @@
...
   private
     def item_params
-      params[:item].permit(:name, :description, :unit_price)
+      params[:item].permit(:name, :description, :enabled)
+    end
+
+    def update_item_details(merchant, item, params)
+      if item.update(item_params.merge(unit_price: price_to_cents(params[:item][:unit_price])))
+        redirect_to merchant_item_path(merchant.id, item.id)
+        flash[:alert] = "Victory! 🥳 This item has been successfully updated."
```
Comment (Sidarth20) [inline app/controllers/merchants/items_controller.rb:41]: Idk how long it took you to find a way to put the emoji in there but that's pretty sweet!

File: app/modules/dollarable.rb [hunk 2]
```diff
@@ -0,0 +1,9 @@
+module Dollarable
```
Comment (Sidarth20) [inline app/modules/dollarable.rb:1]: Excellent work creating a module to help clean up the code in the Item model!!!

File: app/views/merchants/items/edit.html.erb [hunk 3]
```diff
@@ -2,12 +2,12 @@
 
 <h3>Edit <%= @item.name %></h3>
 
-<%= form_with model: @item, url: merchant_item_path(@merchant.id, @item.id), method: :patch, local: true do |f| %>
+<%= form_with model: [@merchant, @item], local: true do |f| %>
```
Comment (Sidarth20) [inline app/views/merchants/items/edit.html.erb:5]: Are you using both the merchant & item models for this form because for each merchant.id, it will have multiple item.id's as well so you need both?

File: app/views/merchants/items/index.html.erb [hunk 4]
```diff
@@ -1,9 +1,23 @@
...
 
-<% @items.each do |item| %>
-  <div id="item-<%= item.id %>">
-    <p><a href="/merchants/<%= @merchant.id %>/items/<%= item.id %>" ><%= item.name %></a></p>
-  </div>
-<% end %>
\ No newline at end of file
+  <% @items.enabled_only.each do |item| %>
+    <div id="item-<%= item.id %>">
+      <p><a href="/merchants/<%= @merchant.id %>/items/<%= item.id %>" ><%= item.name %></a></p>
```
Comment (Sidarth20) [inline app/views/merchants/items/index.html.erb]: Is this line creating a link? Should the syntax be link_to instead of "a href"?

File: spec/features/merchants/items/index_spec.rb [hunk 5]
```diff
@@ -15,15 +15,74 @@
...
+      click_on 'Enable'
+    end
+
+    expect(current_path).to eq "/merchants/#{@merchant.id}/items"
+
+    within "section#enabled" do
+      expect(page).to have_content 'Orchid'
+    end
+
+    within "section#disabled" do
```
Comment (Sidarth20) [inline spec/features/merchants/items/index_spec.rb:84]: Great work with all of your within testing blocks!!!

**Review by Sidarth20 — APPROVED** [review]

File: app/modules/dollarable.rb (hunk 2 above)
Comment (LawrenceWhalen) [inline app/modules/dollarable.rb:1]: Stealing this over to our side...

File: app/controllers/merchants/items_controller.rb [hunk 6]
```diff
@@ -1,32 +1,47 @@
...
 
   def edit
-    @merchant = Merchant.find(params[:merchant_id])
-    @item = Item.find(params[:id])
   end
 
   def update 
+    if params[:item][:enabled].present? && @item.update(item_params)
+      redirect_to merchant_items_path(@merchant.id)
+    else
```
Comment (LawrenceWhalen) [inline app/controllers/merchants/items_controller.rb]: Do we want to pull out just the :enabled from this to prevent updating the item with html hidden edits on our button?

File: app/modules/dollarable.rb (hunk 2 above)
Comment (LawrenceWhalen) [reply app/modules/dollarable.rb:1]: Let me know if I am wrong, but I think this method will drop trailing 0's. Do you check for 8.20 instead of 8.2 anywhere?

**Review by LawrenceWhalen — COMMENTED** [review]
Thanks for doing all the work to add validation. Makes me a happy code monkey.

File: app/controllers/merchants/items_controller.rb (hunk 1 above)
Comment (mkrumholz) [reply app/controllers/merchants/items_controller.rb:41]: @Sidarth20 fun fact: you can use `ctrl + cmd + space` and just type emoji into your IDE like normal!

File: app/views/merchants/items/edit.html.erb (hunk 3 above)
Comment (mkrumholz) [reply app/views/merchants/items/edit.html.erb:5]: Yea, so I think because my resources are all embedded under a merchant, it needs both ids. So my path here is like "/merchants/merchant_id/items/item_id" so to access that particular model, the form needs to know which merchant's item and also which item in particular

File: app/views/merchants/items/index.html.erb (hunk 4 above)
Comment (mkrumholz) [reply app/views/merchants/items/index.html.erb]: Yes! Thanks for the catch. I will update.

Comment (mkrumholz) [reply app/views/merchants/items/index.html.erb]: Updated!

File: app/modules/dollarable.rb (hunk 2 above)
Comment (mkrumholz) [reply app/modules/dollarable.rb:1]: @LawrenceWhalen hmm I took that to be view logic so I do it in the view with `number_to_currency`

File: app/controllers/merchants/items_controller.rb (hunk 6 above)
Comment (mkrumholz) [reply app/controllers/merchants/items_controller.rb]: @LawrenceWhalen I like that, thanks! Will update

File: app/modules/dollarable.rb (hunk 2 above)
Comment (mkrumholz) [reply app/modules/dollarable.rb:1]: Does that seem right to you? ^

Comment (mkrumholz) [reply app/modules/dollarable.rb:1]: I should probably condense my testing here anyway, though, since I refactored into this, the tests are still living elsewhere

File: app/controllers/merchants/items_controller.rb (hunk 6 above)
Comment (mkrumholz) [reply app/controllers/merchants/items_controller.rb]: Updated ^

File: app/modules/dollarable.rb (hunk 2 above)
Comment (mkrumholz) [reply app/modules/dollarable.rb:1]: Reviewed and confirmed that my view logic deals with this issue on the show page. I also updated my edit form, though, so thanks for noting this. I still believe that dealing with trailing 0s belongs in the view still, so I am not going to update that in the module itself.

Comment (mkrumholz) [reply app/modules/dollarable.rb:1]: @LawrenceWhalen sorry meant to tag you there ^
